# Generated by Django 3.2.8 on 2021-11-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_animal', models.CharField(max_length=50)),
                ('name_exercise', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
