# Generated by Django 3.2.8 on 2021-11-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='content',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
